// <auto-generated />
using System;
using BOS.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BOS.Backend.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260221024426_AddSupplierMapset")]
    partial class AddSupplierMapset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("BOS.Backend.Models.GlossaryUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CatalogNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ContractedPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MFR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SupplierId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("supplier_id");

                    b.Property<string>("UnitMetric")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("E");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId", "CatalogNumber")
                        .IsUnique();

                    b.ToTable("GlossaryUnits");
                });

            modelBuilder.Entity("BOS.Backend.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("BOS.Backend.Models.SupplierMapset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ColCatalogNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColMfr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColPrice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColUnitMetric")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SupplierId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("supplier_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId")
                        .IsUnique();

                    b.ToTable("SupplierMapsets");
                });

            modelBuilder.Entity("BOS.Backend.Models.GlossaryUnit", b =>
                {
                    b.HasOne("BOS.Backend.Models.Supplier", "Supplier")
                        .WithMany("GlossaryUnits")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("BOS.Backend.Models.SupplierMapset", b =>
                {
                    b.HasOne("BOS.Backend.Models.Supplier", "Supplier")
                        .WithOne("Mapset")
                        .HasForeignKey("BOS.Backend.Models.SupplierMapset", "SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("BOS.Backend.Models.Supplier", b =>
                {
                    b.Navigation("GlossaryUnits");

                    b.Navigation("Mapset");
                });
#pragma warning restore 612, 618
        }
    }
}
